### ISSUE TITLE
Konnected plugin keeps crashing

### ISSUE THREAD

**Issue by mehrantb** [mkormendy/homebridge-konnected#44]
### Discussed in https://github.com/mkormendy/homebridge-konnected/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **mehrantb** November 15, 2023</sup>
I keep seeing this:

listening port 37625 closed and released
2023-11-15T18:21:21.799Z node-ssdp:client SSDP response: { message: 'HTTP/1.1 200 OK\r\n' + 'DATE: Wed Nov 15 18:21:21 2023\r\n' + 'EXT: \r\n' + 'ST: 239.255.255.250:1900\r\r\n' + 'CACHE-CONTROL: max-age = 1800\r\n' + 'USN: uuid:C0972779-D960-0000-0000-000000000000::urn:SmartHomeAlliance-org:device:Refrigerator:1.5 deviceSubType/Refrigerator modelID/TP6X_REF_16K\r\n' + 'SERVER: Linux/2.6 SHP/1.0 Refrigerator/1.5 deviceSubType/Refrigerator modelID/TP6X_REF_16K\r\n' + 'LOCATION: https://192.168.68.112:8888/capability\r\n' + '\r\n' }
[11/15/2023, 10:21:21 AM] TypeError: Cannot read properties of undefined (reading 'indexOf')
    at SsdpClient.<anonymous> (/var/lib/homebridge/node_modules/homebridge-konnected/src/platform.ts:333:23)
    at SsdpClient.emit (node:events:514:28)
    at SsdpClient.parseResponse [as _parseResponse] (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:457:8)
    at SsdpClient.SSDP._parseMessage (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:298:10)
    at Socket.onSocketMessage (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:244:12)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
    
Here is my config:

`{
    "bridge": {
        "name": "Homebridge 6442",
        "username": "<NAME>",
        "port": 51688,
        "pin": "<>",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Konnected",
            "panels": [
                {
                    "name": "Konnected V1-V2",
                    "uuid": "<UUID>",
                    "ipAddress": "192.168.68.144",
                    "port": 13679,
                    "zones": [
                        {
                            "enabled": true,
                            "zoneNumber": "1",
                            "zoneType": "motion",
                            "zoneLocation": "Formal Living Room"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "2",
                            "zoneType": "contact",
                            "zoneLocation": "Side Yard"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "3",
                            "zoneType": "contact",
                            "zoneLocation": "Den"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "4",
                            "zoneType": "contact",
                            "zoneLocation": "Breakfast Nook"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "5",
                            "zoneType": "contact",
                            "zoneLocation": "Master Bedroom"
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "6",
                            "zoneType": "contact",
                            "zoneLocation": "Bedroom"
                        }
                    ]
                }
            ],
            "platform": "konnected"
        }
    ],
    "disabledPlugins": []
}`</div>

**Comment by mkormendy** [comment]
First off, try changing your Homebridge advertiser to Ciao (not bonjour-hap).
Beyond that, I am seeing a refrigerator respond to the SSDP broadcast request, and it's invalid for the Konnected plugin's requirements.
Is this still happening?
While not a solution, to troubleshoot, temporarily disconnect your fridge from your wifi network and see if this error occurs anymore. Let me know if it does.

**Comment by mkormendy** [comment]
Stale, no response.
