### ISSUE TITLE
Konnected Plugin keeps restarting

### ISSUE THREAD

**Issue by macinapp** [mkormendy/homebridge-konnected#54]
It's a new install. I got the Konnected board today and tried to install the plugin for my Homebridge instance with multiple pluginsthat's been running on a Mac for years.

  I tried to switch Ciao protocol with no success. It looks like the plugin is actually working but because it restarts every few seconds is not usable at that point. I have tried to re-install a few times but no difference.

Here is the log with errors:

===============================
[4/27/2024, 10:08:21 PM] Homebridge v1.8.1 (HAP v0.12.0) (Konnected) is running on port 52476.
[4/27/2024, 10:08:21 PM] [Konnected] Listening for zone changes on 192.168.10.19 port 5000
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at SsdpClient.<anonymous> (file:///usr/local/lib/node_modules/homebridge-konnected/src/platform.ts:353:23)
    at SsdpClient.emit (node:events:518:28)
    at SsdpClient.parseResponse [as _parseResponse] (/usr/local/lib/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:457:8)
    at SsdpClient.SSDP._parseMessage (/usr/local/lib/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:298:10)
    at Socket.onSocketMessage (/usr/local/lib/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:244:12)
    at Socket.emit (node:events:518:28)
    at UDP.onMessage (node:dgram:942:8)
[4/27/2024, 10:08:22 PM] [Konnected] Child bridge process ended
[4/27/2024, 10:08:22 PM] [Konnected] Process Ended. Code: 1, Signal: null
===============================

This is a debug log. Please let me know if you need anything else.

Thank you.

**Comment by mkormendy** [comment]
I will need more details, please fill out the following details per the bug report:

**Describe the bug**
Replaee this text with a clear and concise description of what the bug or issue is.

**To Reproduce**
Replace this text with steps to reproduce the bug or issue you're having:
1. Go to '...'
2. Open door '....'
3. Open Home.app '....'
4. Result unexpected

**Expected Behavior**
Replace this text with a clear and concise description of what you expected to happen.

**Environment (please complete the following information as best possible)**
* Homebridge System:
  * Node.js Version
  * NPM Version: 
  * Homebridge/HOOBS Version
  * Operating System: *(Raspbian / Ubuntu / Debian / Windows / macOS / Docker)*
  * Process Supervisor: *(Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none)
* Konnected Panel(s):
  * Panel Hardware Version
  * Firmware Version
  * Addon Panel(s)
  * Interface Panel(s)

**Attach Files to Support Your Experience**
 - Screenshots of your Konnected App device settings screen
 - Debug Log ([turn on debugging in Homebridge/HOOBS](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode) and copy the results into a text file starting from boot up to shortly after the where the issue occurs)
 - Homebridge/HOOBS config.json file and or plugin section from the config.json found in your [```.homebridge folder```](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#understanding-where-your-files-are-macos).

**Additional Relevant Information**
Replace this text with any other context about the problem here.
